# make makefile
# 
# Tools used:
#  Compile::Resource Compiler
#  Compile::GNU C
#  Make: make
all : ToLower.exe

ToLower.exe : tolower.obj tolower.def tolower.res  
	gcc -Zomf tolower.obj tolower.def -o ToLower.exe
	wrc tolower.res

tolower.obj : tolower.c 
	gcc -Wall -Zomf -c -O2 tolower.c -o tolower.obj

tolower.res : tolower.rc 
	wrc -r tolower.rc

clean :
	rm -rf *exe *res *obj *lib